apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: mrsabin/django-app:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: django-secrets
            command: ['python', 'manage.py', 'clearsessions']
          restartPolicy: OnFailure