apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["apt update && apt install -y postgresql-client && sleep infinity"]
    volumeMounts:
      - name: secret-volume
        mountPath: /root/.postgresql
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  restartPolicy: Always
