apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
            envFrom:
              - configMapRef:
                  name: django-config
            command: ['python', 'manage.py', 'clearsessions']
          restartPolicy: OnFailure

